document.title = "DOM in JS";
document.body.style.backgroundColor="pink";
document.body.style.backgroundImage="url('backgroundimg.png')";
document.body.style.backgroundRepeat="no-repeat";
document.body.style.backgroundSize="cover";
document.getElementById("header").innerHTML = "Welcom to DOM";
document.getElementById("header").style.border ="2.5px solid black";
document.getElementById("header").style.color="silver"
document.getElementById("header").style.textAlign="center";
document.getElementsByTagName("img")[0].style.padding="5px 45% 5px 45%";
document.getElementsByTagName("img")[0].style.height="150px"
document.getElementsByTagName("img")[0].style.width="150px"
document.getElementById("para").innerHTML = "Welcome to MRCET";
document.getElementById("para").style.color = "gold";
document.getElementById("para").style.fontSize = "30px";
document.getElementsByClassName("dspn")[0].innerHTML="The Branches in Our Collage";
document.getElementsByClassName("dspn")[0].style.color="black";
document.getElementsByClassName("csd")[0].style.color="orange";
document.getElementsByClassName("cs")[0].style.color="darkBlue";
document.getElementsByClassName("csm")[0].style.color="brown";
document.getElementsByClassName("it")[0].style.color="grey";
